function H = jac(vec,sensor_pos,stick_length)
a = vec(1);
b = vec(2);
c = vec(3);
d = vec(4);
e = vec(5);
f = vec(6);
x = sensor_pos(1);
y = sensor_pos(2);
s = stick_length;

H = [[                                                                                                                                                                                                                    (2*real(a) - 2*real(x) + cos(real(e))*real(s))/(2*((real(a) - real(x) + (cos(real(e))*real(s))/2)^2 + (real(b) - real(y) + (sin(real(e))*real(s))/2)^2)^(1/2)),                                                                                                                                                                                                                     (2*real(b) - 2*real(y) + sin(real(e))*real(s))/(2*((real(a) - real(x) + (cos(real(e))*real(s))/2)^2 + (real(b) - real(y) + (sin(real(e))*real(s))/2)^2)^(1/2)),                                                                               0,                                                                               0,                                                                                                      -(sin(real(e))*real(s)*(real(a) - real(x) + (cos(real(e))*real(s))/2) - cos(real(e))*real(s)*(real(b) - real(y) + (sin(real(e))*real(s))/2))/(2*((real(a) - real(x) + (cos(real(e))*real(s))/2)^2 + (real(b) - real(y) + (sin(real(e))*real(s))/2)^2)^(1/2)),                                                                                                                                                                       0];...
[                                                                                                                                                                                                                             -(real(b) - real(y) + (sin(real(e))*real(s))/2)/((real(a) - real(x) + (cos(real(e))*real(s))/2)^2 + (real(b) - real(y) + (sin(real(e))*real(s))/2)^2),                                                                                                                                                                                                                               (real(a) - real(x) + (cos(real(e))*real(s))/2)/((real(a) - real(x) + (cos(real(e))*real(s))/2)^2 + (real(b) - real(y) + (sin(real(e))*real(s))/2)^2),                                                                               0,                                                                               0, (((cos(real(e))*real(s))/(2*(real(a) - real(x) + (cos(real(e))*real(s))/2)) + (sin(real(e))*real(s)*(real(b) - real(y) + (sin(real(e))*real(s))/2))/(2*(real(a) - real(x) + (cos(real(e))*real(s))/2)^2))*(real(a) - real(x) + (cos(real(e))*real(s))/2)^2)/((real(a) - real(x) + (cos(real(e))*real(s))/2)^2 + (real(b) - real(y) + (sin(real(e))*real(s))/2)^2),                                                                                                                                                                       0];...
[(real(c) + (cos(pi/2 + real(e))*real(f)*real(s))/2)/(abs(real(a) - real(x))^2 + abs(real(b) - real(y))^2)^(1/2) - (abs(real(a) - real(x))*sign(real(a) - real(x))*((real(c) + (cos(pi/2 + real(e))*real(f)*real(s))/2)*(real(a) - real(x)) + (real(d) + (sin(pi/2 + real(e))*real(f)*real(s))/2)*(real(b) - real(y))))/(abs(real(a) - real(x))^2 + abs(real(b) - real(y))^2)^(3/2), (real(d) + (sin(pi/2 + real(e))*real(f)*real(s))/2)/(abs(real(a) - real(x))^2 + abs(real(b) - real(y))^2)^(1/2) - (abs(real(b) - real(y))*sign(real(b) - real(y))*((real(c) + (cos(pi/2 + real(e))*real(f)*real(s))/2)*(real(a) - real(x)) + (real(d) + (sin(pi/2 + real(e))*real(f)*real(s))/2)*(real(b) - real(y))))/(abs(real(a) - real(x))^2 + abs(real(b) - real(y))^2)^(3/2), (real(a) - real(x))/(abs(real(a) - real(x))^2 + abs(real(b) - real(y))^2)^(1/2), (real(b) - real(y))/(abs(real(a) - real(x))^2 + abs(real(b) - real(y))^2)^(1/2),                                                                                                                                                                           ((cos(pi/2 + real(e))*real(f)*real(s)*(real(b) - real(y)))/2 - (sin(pi/2 + real(e))*real(f)*real(s)*(real(a) - real(x)))/2)/(abs(real(a) - real(x))^2 + abs(real(b) - real(y))^2)^(1/2), ((cos(pi/2 + real(e))*real(s)*(real(a) - real(x)))/2 + (sin(pi/2 + real(e))*real(s)*(real(b) - real(y)))/2)/(abs(real(a) - real(x))^2 + abs(real(b) - real(y))^2)^(1/2)]];
 
end